language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - setup=basic
  matrix:
    - ADAPTER=Apc
    - ADAPTER=Ev

services:
  - memcached
  - mongodb
  - redis-server

matrix:
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - if [[ $ADAPTER = 'Apc' ]]; then chmod a+x ./build/travis/Apc.sh; ./build/travis/Apc.sh; fi
  - if [[ $ADAPTER = 'Ev' ]]; then chmod a+x ./build/travis/ev.sh; ./build/travis/ev.sh; fi
  - if [[ $PHP_VERSION != 'hhvm' ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

before_install:
  - composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - OCULAR_ENV='5.6'

install:
  - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer.phar
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - php -n php-cs-fixer.phar fix -v --dry-run
  - vendor/bin/phpunit --verbose --coverage-clover clover-data
  - if [ $(phpenv version-name) = $OCULAR_ENV ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover clover-data; fi

after_script:
  - php vendor/bin/coveralls -v

sudo: false
